#!/usr/bin/env python3
"""Render the Raze device files that repeat hardware facts from manifest.json.

devices/raze/manifest.json is the single source of truth for the board's
hardware (LED ring, fan, camera, I2C devices, watchdog) and kernel. This tool
writes the files and file regions derived from it, and lints the manifest
itself, including that its kernel facts match gaia/kernel.toml and the kernel
fragment (which it only reads):

    devices/tools/gen-raze.py            rewrite the generated files
    devices/tools/gen-raze.py --check    change nothing; print a diff and exit 1
                                         when anything disagrees with the manifest

Generated output is committed (Gaia has no step that runs a script at package
build time), and the --check lint in CI keeps it in step with the manifest.
Whole generated files start with a "generated" header; generated regions inside
hand-written files sit between `>>> gen-raze: <name>` and `<<< gen-raze` marker
comments. Edit the manifest, not those parts.

It also renders lemnosd's board definition (gaia/assets/rootfs/etc/lemnos/
board.toml, see raze_lemnos.py) and validates it against Lemnos's JSON Schema
and driver rules; with a lemnos-ctl (--lemnos-ctl, $LEMNOS_CTL or PATH) it runs
`lemnos-ctl validate` on it as well.

Python 3.11+ standard library only.
"""

from __future__ import annotations

import argparse
import difflib
import json
import os
import re
import shutil
import sys
import tempfile
from pathlib import Path

sys.dont_write_bytecode = True  # no __pycache__ next to the tool
sys.path.insert(0, str(Path(__file__).resolve().parent))
import raze_lemnos  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
PKG = ROOT / "devices" / "raze"
MANIFEST = PKG / "manifest.json"
GAIA = PKG / "gaia"
BOOT = GAIA / "assets" / "boot"
ROOTFS = GAIA / "assets" / "rootfs"
LIBDIR = ROOTFS / "usr" / "lib" / "board"

LEMNOS_SCHEMA = ROOT / "devices" / "schema" / "lemnos-board.schema.json"

SOURCE = "devices/raze/manifest.json"
TOOL = "devices/tools/gen-raze.py"

WIRE_FORMATS = {"grb24", "rgb24", "grbw32", "rgbw32"}
LAYOUT = re.compile(r"^(?!.*(.).*\1)[rgbw]{4}$")
POLARITIES = {"normal": 0, "inversed": 1}


class LintError(Exception):
    pass


def header(comment: str) -> str:
    return (
        f"{comment} Generated by {TOOL} from {SOURCE}; do not edit.\n"
        f"{comment} Change the manifest and run the tool (CI runs it with --check).\n"
    )


def sh_quote(value: object) -> str:
    text = str(value)
    if re.fullmatch(r"[A-Za-z0-9_.,:/%+-]*", text):
        return text
    return "'" + text.replace("'", "'\\''") + "'"


def hexaddr(value: int) -> str:
    return f"0x{value:02x}"


# ---------------------------------------------------------------------------
# Lint: the manifest's hardware sections are complete and consistent.


def lookup(section: dict, path: str):
    node = section
    for part in path.split("."):
        if isinstance(node, list) and part.isdigit() and int(part) < len(node):
            node = node[int(part)]
            continue
        if not isinstance(node, dict) or part not in node:
            raise KeyError(path)
        node = node[part]
    return node


def lint_verified(name: str, section: dict, required: list[str]) -> None:
    where = name if "." in name or name == "kernel" else f"capabilities.{name}"
    notes = section.get("verified")
    if not isinstance(notes, dict):
        raise LintError(f"{where}.verified is missing")
    for fact, note in notes.items():
        try:
            lookup(section, fact)
        except KeyError:
            raise LintError(f"{where}.verified names {fact}, which the section doesn't have")
        if note == "unverified":
            continue
        if not isinstance(note, dict) or set(note) != {"by", "date", "method"}:
            raise LintError(f'{where}.verified.{fact} must be "unverified" or {{"by", "date", "method"}}')
        if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", str(note["date"])):
            raise LintError(f"{where}.verified.{fact}.date must be YYYY-MM-DD")
        if not str(note["by"]).strip() or not str(note["method"]).strip():
            raise LintError(f"{where}.verified.{fact} needs who and how")
    for fact in required:
        if fact not in notes:
            raise LintError(f"{where}.verified.{fact} is missing (a note or \"unverified\")")


def lint_kernel(manifest: dict) -> None:
    """The kernel facts agree with the files that build the kernel (read only)."""
    kernel = manifest.get("kernel")
    if not isinstance(kernel, dict):
        raise LintError("kernel is missing")
    for key in ("commit", "version", "defconfig", "page_size_kib", "fragment", "fragment_merge"):
        if key not in kernel:
            raise LintError(f"kernel.{key} is missing")
    if kernel["page_size_kib"] not in (4, 16, 64):
        raise LintError("kernel.page_size_kib must be 4, 16 or 64")
    if kernel["fragment_merge"] != "os-first-package-last":
        raise LintError('kernel.fragment_merge must be "os-first-package-last"')
    toml = (GAIA / "kernel.toml").read_text()
    if kernel["commit"] not in toml:
        raise LintError(f"kernel.commit {kernel['commit'][:12]} is not the one gaia/kernel.toml builds")
    defconfig = re.search(r'"BR2_LINUX_KERNEL_DEFCONFIG",\s*"\\"([^"\\]+)\\""', toml)
    if not defconfig or defconfig.group(1) != kernel["defconfig"]:
        raise LintError(f"kernel.defconfig {kernel['defconfig']} is not the one gaia/kernel.toml sets")
    fragment = PKG / kernel["fragment"]
    if not fragment.is_file():
        raise LintError(f"kernel.fragment {kernel['fragment']} doesn't exist")
    config = fragment.read_text()
    for feature in kernel.get("builtin", []):
        if not re.search(rf"^CONFIG_{re.escape(feature.upper())}_FS=y$|^CONFIG_{re.escape(feature.upper())}=y$", config, re.M):
            raise LintError(f"kernel.builtin lists {feature}, but {kernel['fragment']} doesn't build it in")
    # The page size Buildroot applies (BR2_ARM64_PAGE_SIZE_*, which wins over
    # fragments) and the one raze.config states must both be the manifest's.
    size = f"{kernel['page_size_kib']}K"
    if f'["BR2_ARM64_PAGE_SIZE_{size}", "y"]' not in toml:
        raise LintError(f"kernel.page_size_kib is {kernel['page_size_kib']}, but gaia/kernel.toml doesn't set BR2_ARM64_PAGE_SIZE_{size}")
    if not re.search(rf"^CONFIG_ARM64_{size}_PAGES=y$", config, re.M):
        raise LintError(f"kernel.page_size_kib is {kernel['page_size_kib']}, but {kernel['fragment']} doesn't set CONFIG_ARM64_{size}_PAGES=y")
    lint_verified("kernel", kernel, ["page_size_kib"])


def is_int(value: object) -> bool:
    return isinstance(value, int) and not isinstance(value, bool)


def lint(manifest: dict) -> None:
    lint_kernel(manifest)
    caps = manifest.get("capabilities") or {}
    for name in ("leds", "fan", "camera", "i2c", "watchdog"):
        if not isinstance(caps.get(name), dict):
            raise LintError(f"capabilities.{name} is missing")

    leds = caps["leds"]
    for key in ("part", "gpio", "count", "device", "brightness", "wire_format"):
        if key not in leds:
            raise LintError(f"capabilities.leds.{key} is missing")
    if leds["wire_format"] not in WIRE_FORMATS:
        raise LintError(f"capabilities.leds.wire_format must be one of {sorted(WIRE_FORMATS)}")
    if leds.get("rgbw", False) != leds["wire_format"].endswith("32"):
        raise LintError("capabilities.leds.rgbw must match wire_format (true only for 32-bit LEDs)")
    layout = leds.get("userspace", {}).get("layout", "")
    if not LAYOUT.fullmatch(layout) or leds["userspace"].get("bytes_per_led") != 4:
        raise LintError("capabilities.leds.userspace must be a 4-letter layout of r, g, b, w with bytes_per_led 4")
    count = leds["count"]
    if not is_int(count) or count < 1:
        raise LintError("capabilities.leds.count must be a positive integer")
    index = leds.get("index", {})
    if not is_int(index.get("offset")) or not 0 <= index["offset"] < count:
        raise LintError("capabilities.leds.index.offset must be an integer in 0..count-1")
    if index.get("direction") not in (1, -1):
        raise LintError("capabilities.leds.index.direction must be 1 or -1")
    if not is_int(leds["brightness"]) or not 0 <= leds["brightness"] <= 255:
        raise LintError("capabilities.leds.brightness must be 0..255")
    lint_verified("leds", leds, ["part", "wire_format", "userspace.layout", "gpio", "count", "index.offset", "index.direction"])

    fan = caps["fan"]
    pwm = fan.get("pwm", {})
    for key in ("controller", "channel", "period_ns", "polarity"):
        if key not in pwm:
            raise LintError(f"capabilities.fan.pwm.{key} is missing")
    if pwm["polarity"] not in POLARITIES:
        raise LintError(f"capabilities.fan.pwm.polarity must be one of {sorted(POLARITIES)}")
    levels = fan.get("cooling_levels", [])
    trips = fan.get("trips_c", [])
    if len(levels) != 5 or not all(is_int(v) and 0 <= v <= fan.get("level_max", 255) for v in levels):
        raise LintError("capabilities.fan.cooling_levels must be 5 integers in 0..level_max (the overlay has level0..level4)")
    if levels != sorted(levels):
        raise LintError("capabilities.fan.cooling_levels must not decrease")
    if len(trips) != len(levels) - 1 or trips != sorted(trips):
        raise LintError("capabilities.fan.trips_c must be one rising trip per level after the first")
    if fan.get("min_level") != min(levels):
        raise LintError("capabilities.fan.min_level must equal the lowest cooling level")
    lint_verified("fan", fan, ["pwm.controller", "pwm.channel", "pwm.period_ns", "pwm.polarity", "cooling_levels", "trips_c"])

    cam = caps["camera"]
    if cam.get("i2c_address") != cam.get("i2c", {}).get("address"):
        raise LintError("capabilities.camera.i2c_address and i2c.address disagree")
    if not is_int(cam.get("i2c", {}).get("address")):
        raise LintError("capabilities.camera.i2c.address must be a number")
    lint_verified("camera", cam, ["part", "i2c.address", "i2c.bus"])

    i2c = caps["i2c"]
    buses = {bus["bus"]: bus for bus in i2c.get("buses", [])}
    ids = set()
    for device in i2c.get("devices", []):
        where = f"capabilities.i2c.devices[{device.get('id')}]"
        if device.get("id") in ids or not device.get("id"):
            raise LintError(f"{where}: every device needs a unique id")
        ids.add(device["id"])
        if device.get("bus") not in buses:
            raise LintError(f"{where}: bus {device.get('bus')} is not in capabilities.i2c.buses")
        address = device.get("address")
        if not is_int(address) or not 0x03 <= address <= 0x77:
            raise LintError(f"{where}: address must be a 7-bit number (0x03..0x77)")
    for bus in buses.values():
        for key in ("sda_gpio", "scl_gpio", "overlay"):
            if key not in bus:
                raise LintError(f"capabilities.i2c.buses[{bus['bus']}].{key} is missing")
        select = {k: v for k, v in bus.get("select", {}).items() if k in raze_lemnos.SELECTOR_KEYS}
        if "select" in bus and (
            not select or any(not isinstance(v, str) or not v or ";" in v or " " in v for v in select.values())
        ):
            raise LintError(
                f"capabilities.i2c.buses[{bus['bus']}].select needs name, compatible, of or node (no spaces or ;)"
            )
    for device in i2c.get("devices", []):
        where = f"capabilities.i2c.devices[{device['id']}]"
        chip = device.get("chip_id")
        if chip is not None:
            if chip.get("width") not in (8, 16) or not is_int(chip.get("register")) or not is_int(chip.get("value")):
                raise LintError(f"{where}.chip_id needs register, width (8 or 16) and value")
            if chip["width"] == 16 and chip.get("smbus_word") != ((chip["value"] & 0xFF) << 8 | chip["value"] >> 8):
                raise LintError(f"{where}.chip_id.smbus_word must be the value byte-swapped (SMBus words are little-endian)")
        ld = device.get("lemnosd")
        if ld is not None and ("device" not in ld or ("driver" in ld) == ("config" in ld)):
            raise LintError(f"{where}.lemnosd needs device and either driver (with poll_ms) or config")
        if ld and ld.get("driver") in ("ina226", "ina238") and not ("shunt_ohm" in device and "max_current_a" in device):
            raise LintError(f"{where}: an INA power monitor needs shunt_ohm and max_current_a for lemnosd")
    lint_verified("i2c", i2c, ["buses", "devices"])

    wd = caps["watchdog"]
    for key in ("device", "runtime_sec", "reboot_sec"):
        if key not in wd:
            raise LintError(f"capabilities.watchdog.{key} is missing")
    lint_verified("watchdog", wd, ["device"])

    for name, keys in (
        ("leds", ["device"]),
        ("fan", ["device", "thermal_device", "poll_ms", "writers"]),
        ("usb-power", ["device", "port"]),
    ):
        block = caps.get(name, {}).get("lemnosd")
        if not isinstance(block, dict) or any(k not in block for k in keys):
            raise LintError(f"capabilities.{name}.lemnosd needs {', '.join(keys)}")
    if "board-selftest" not in caps["fan"]["lemnosd"]["writers"]:
        raise LintError("capabilities.fan.lemnosd.writers must include board-selftest, the self-test's lemnosd client")
    lint_hardware_service(caps.get("hardware-service"))


def lint_hardware_service(service: dict | None) -> None:
    """The Lemnos pin agrees with the layer that imports it and with the docs."""
    if not isinstance(service, dict):
        raise LintError("capabilities.hardware-service is missing")
    imp = service.get("gaia_import", {})
    rev = imp.get("rev", "")
    if not re.fullmatch(r"[0-9a-f]{40}", rev):
        raise LintError("capabilities.hardware-service.gaia_import.rev must be a full commit sha")
    layer = (GAIA / "lemnos.toml").read_text()
    if f'{{ source = "{imp.get("source")}", path = "{imp.get("path")}" }}' not in layer:
        raise LintError("gaia/lemnos.toml must import the manifest's gaia_import source and path")
    for doc in (GAIA / "lemnos.toml", GAIA / "device.toml", ROOT / "devices" / "README.md"):
        if f'rev = "{rev}"' not in doc.read_text():
            raise LintError(f'{doc.relative_to(ROOT)} must show the Lemnos pin rev = "{rev}"')
    env = (GAIA / "assets" / "lemnos" / "lemnosd.env").read_text()
    if f"LEMNOSD_UPDATE_STATUS={service.get('update_status')}\n" not in env:
        raise LintError("gaia/assets/lemnos/lemnosd.env must set LEMNOSD_UPDATE_STATUS to hardware-service.update_status")


# ---------------------------------------------------------------------------
# Renderers.


def leds_overlay_line(leds: dict) -> str:
    params = [
        leds["overlay"]["name"],
        f"gpio={leds['gpio']}",
        f"num_leds={leds['count']}",
        f"brightness={leds['brightness']}",
    ]
    if leds["wire_format"].endswith("32"):
        params.append("rgbw")
    params.append(f"dev_name={leds['overlay']['dev_name']}")
    return "dtoverlay=" + ",".join(params)


def region_device_txt(manifest: dict) -> dict[str, str]:
    caps = manifest["capabilities"]
    leds = caps["leds"]
    i2c_lines = []
    for bus in caps["i2c"]["buses"]:
        kind = "Hardware" if bus["kind"] == "hardware" else "Software (i2c-gpio)"
        parts = sorted({d["part"] for d in caps["i2c"]["devices"] if d["bus"] == bus["bus"]})
        i2c_lines.append(
            f"# {kind} I2C bus {bus['bus']} (/dev/i2c-{bus['bus']}): SDA GPIO{bus['sda_gpio']}, "
            f"SCL GPIO{bus['scl_gpio']}; {', '.join(parts)}.\n"
            f"dtoverlay={bus['overlay']}\n"
        )
    wire = leds["wire_format"]
    bits = 32 if wire.endswith("32") else 24
    leds_text = (
        f"# Status LED ring: {leds['count']} {leds['part']} LEDs ({bits}-bit {wire[:-2].upper()} on the wire)\n"
        f"# on GPIO{leds['gpio']} via RP1 PIO, {leds['device']}."
        + (
            " No `rgbw`: that sends 32 bits per LED and\n# smears the colours around the ring.\n"
            if bits == 24
            else "\n"
        )
        + leds_overlay_line(leds)
        + "\n"
    )
    cam = caps["camera"]
    cam_text = (
        f"# {cam['part']} global-shutter camera on {cam['port'].upper()}"
        f"{', continuous clock' if cam['csi'].get('clock_continuous') else ''}.\n"
        "camera_auto_detect=0\n"
        f"dtoverlay={cam['overlay']}\n"
    )
    return {"i2c": "".join(i2c_lines), "leds": leds_text, "camera": cam_text}


def region_fan_dts(manifest: dict) -> dict[str, str]:
    fan = manifest["capabilities"]["fan"]
    pwm = fan["pwm"]
    levels = " ".join(str(v) for v in fan["cooling_levels"])
    flags = POLARITIES[pwm["polarity"]]
    return {
        "fan": (
            f"\t\t\tcooling-levels = <{levels}>;\n"
            f"\t\t\t/* {pwm['controller']} channel {pwm['channel']}, {pwm['period_ns']} ns, {pwm['polarity']} polarity */\n"
            f"\t\t\tpwms = <&{pwm['controller']} {pwm['channel']} {pwm['period_ns']} {flags}>;\n"
        )
    }


def render_leds_env(manifest: dict) -> str:
    leds = manifest["capabilities"]["leds"]
    lines = [
        header("#"),
        "#\n",
        "# LED ring defaults for raze-leds and the selftest. Each value yields to the\n",
        "# environment; OS and user overrides go in raze-leds.env (in /etc/board or\n",
        "# /data/board), which raze-leds reads after this file.\n",
        "#\n",
        f"# {leds['part']}: {leds['wire_format']} on the wire. The driver reads\n",
        f"# {leds['userspace']['bytes_per_led']} bytes per LED in {leds['userspace']['layout']} order and drops "
        f"{', '.join(c.upper() for c in leds['userspace'].get('ignored_channels', [])) or 'nothing'}.\n",
        "# Logical LED i is driver slot (OFFSET + DIRECTION * i) mod COUNT.\n",
        f"RAZE_LEDS_DEVICE=${{RAZE_LEDS_DEVICE:-{leds['device']}}}\n",
        f"RAZE_LEDS_COUNT=${{RAZE_LEDS_COUNT:-{leds['count']}}}\n",
        f"RAZE_LEDS_ORDER=${{RAZE_LEDS_ORDER:-{leds['userspace']['layout']}}}\n",
        f"RAZE_LEDS_OFFSET=${{RAZE_LEDS_OFFSET:-{leds['index']['offset']}}}\n",
        f"RAZE_LEDS_DIRECTION=${{RAZE_LEDS_DIRECTION:-{leds['index']['direction']}}}\n",
    ]
    return "".join(lines)


def render_hardware_env(manifest: dict) -> str:
    caps = manifest["capabilities"]
    leds, fan, cam, i2c, wd = (caps[k] for k in ("leds", "fan", "camera", "i2c", "watchdog"))
    devices = " ".join(f"{d['id']}:{d['bus']}:{hexaddr(d['address'])}:{d['part']}" for d in i2c["devices"])
    buses = " ".join(
        f"{b['bus']}:{raze_lemnos.bus_ref(caps, b['bus'])[4:]}" for b in i2c["buses"] if b.get("select")
    )
    chip_ids = []
    for d in i2c["devices"]:
        chip = d.get("chip_id")
        if not chip:
            continue
        wide = chip["width"] == 16
        value = chip["smbus_word"] if wide else chip["value"]
        entry = f"{d['id']}:{hexaddr(chip['register'])}:{'w' if wide else 'b'}:0x{value:0{chip['width'] // 4}x}"
        if "power_control" in chip:
            entry += f":{hexaddr(chip['power_control']['register'])}.{chip['power_control']['bit']}"
        chip_ids.append(entry)
    ids = " ".join(chip_ids)
    lemnos = " ".join(f"{d['id']}:{d['lemnosd']['device']}" for d in i2c["devices"] if d.get("lemnosd"))
    values = [
        ("HW_MODEL", manifest["model"]),
        ("HW_LEDS_DEVICE", leds["device"]),
        ("HW_LEDS_COUNT", leds["count"]),
        ("HW_LEDS_PART", leds["part"]),
        ("HW_LEDS_WIRE", leds["wire_format"]),
        ("HW_FAN_COOLING_TYPE", fan["cooling_device_type"]),
        ("HW_FAN_HWMON", fan["hwmon_name"]),
        ("HW_FAN_LEVELS", " ".join(str(v) for v in fan["cooling_levels"])),
        ("HW_FAN_TRIPS_C", " ".join(str(v) for v in fan["trips_c"])),
        ("HW_CAMERA_PART", cam["part"]),
        ("HW_CAMERA_SENSOR", cam["sensor"]),
        ("HW_CAMERA_DRIVER", cam["kernel_driver"]),
        ("HW_CAMERA_ADDRESS", hexaddr(cam["i2c"]["address"])),
        ("HW_CAMERA_RECEIVER", cam["csi"]["receiver_driver"]),
        ("HW_I2C_DEVICES", devices),
        ("HW_I2C_BUSES", buses),
        ("HW_I2C_IDS", ids),
        ("HW_LEMNOS_DEVICES", lemnos),
        ("HW_LEMNOS_RING", leds["lemnosd"]["device"]),
        ("HW_LEMNOS_FAN", fan["lemnosd"]["device"]),
        ("HW_LEMNOS_THERMAL", fan["lemnosd"]["thermal_device"]),
        ("HW_WATCHDOG_DEVICE", wd["device"]),
        ("HW_WATCHDOG_RUNTIME_SEC", wd["runtime_sec"]),
    ]
    body = "".join(f"{name}={sh_quote(value)}\n" for name, value in values)
    return (
        header("#")
        + "#\n# Hardware facts for /usr/lib/board/selftest and hw.sh. HW_I2C_DEVICES is\n"
        + "# id:bus:address:part per device (bus: its number on the 7.2.9 image, a hint).\n"
        + "# HW_I2C_BUSES is bus:selector, the Lemnos i2c: selector that finds a bus\n"
        + "# whatever its number. HW_I2C_IDS is id:register:b|w:value[:register.bit], the\n"
        + "# chip id as i2cget reads it (w: an SMBus word, so byte-swapped) and the power\n"
        + "# control bit to set first. HW_LEMNOS_* are device ids in board.toml.\n"
        + body
    )


def render_sensors_toml(manifest: dict) -> str:
    out = [header("#"), "schema_version = 1\n\n[sensors]\n"]
    for device in manifest["capabilities"]["i2c"]["devices"]:
        out.append("\n  [[sensors.devices]]\n")
        out.append(f'  driver = "{device.get("part_number", device["part"])}"\n')
        out.append(f"  bus = {device['bus']}\n")
        out.append(f"  address = {hexaddr(device['address'])}\n")
        if "shunt_ohm" in device:
            out.append(f"  shunt_resistance = {device['shunt_ohm']:.3f}\n")
        if "current_scale" in device:
            out.append(f"  current_scale = {float(device['current_scale'])}\n")
    return "".join(out)


def render_watchdog_conf(manifest: dict) -> str:
    wd = manifest["capabilities"]["watchdog"]
    reboot = wd["reboot_sec"]
    reboot_text = f"{reboot // 60}min" if reboot % 60 == 0 else f"{reboot}s"
    return (
        header("#")
        + "#\n# A trial boot that hangs must not stay hung: the hardware watchdog resets the\n"
        + "# board, and the bootloader then starts the confirmed slot again.\n"
        + "[Manager]\n"
        + f"RuntimeWatchdogSec={wd['runtime_sec']}s\n"
        + f"RebootWatchdogSec={reboot_text}\n"
    )


# ---------------------------------------------------------------------------
# Regions in hand-written files.


def replace_regions(text: str, regions: dict[str, str], comment: tuple[str, str], path: Path) -> str:
    start, end = comment
    for name, body in regions.items():
        pattern = re.compile(
            rf"(^[ \t]*{re.escape(start)} >>> gen-raze: {re.escape(name)}\b[^\n]*\n)(.*?)(^[ \t]*{re.escape(start)} <<< gen-raze\b[^\n]*\n)",
            re.S | re.M,
        )
        if len(pattern.findall(text)) != 1:
            raise LintError(f"{path.relative_to(ROOT)}: expected one `gen-raze: {name}` region")
        text = pattern.sub(lambda m: m.group(1) + body + m.group(3), text)
    return text


BOARD_TOML = ROOTFS / "etc" / "lemnos" / "board.toml"


def render_board_toml(manifest: dict) -> str:
    """lemnosd's board definition, checked against Lemnos's schema and drivers."""
    board, notes = raze_lemnos.board_definition(manifest, manifest["package_version"])
    text = raze_lemnos.to_toml(board, notes, header("#"))
    try:
        raze_lemnos.check(board, text, LEMNOS_SCHEMA)
    except raze_lemnos.BoardError as error:
        raise LintError(str(error))
    return text


def outputs(manifest: dict) -> dict[Path, str]:
    device_txt = BOOT / "raze-device.txt"
    fan_dts = BOOT / "overlays" / "raze-fan-overlay.dts"
    return {
        device_txt: replace_regions(device_txt.read_text(), region_device_txt(manifest), ("#", ""), device_txt),
        fan_dts: replace_regions(fan_dts.read_text(), region_fan_dts(manifest), ("/*", "*/"), fan_dts),
        LIBDIR / "leds.env": render_leds_env(manifest),
        LIBDIR / "hardware.env": render_hardware_env(manifest),
        ROOTFS / "usr" / "share" / "board" / "raze" / "sensors.toml": render_sensors_toml(manifest),
        ROOTFS / "usr" / "lib" / "systemd" / "system.conf.d" / "60-board-watchdog.conf": render_watchdog_conf(manifest),
        BOARD_TOML: render_board_toml(manifest),
    }


def staged_in_runtime(paths: list[Path]) -> list[str]:
    """Generated rootfs files the runtime layer doesn't stage."""
    runtime = (GAIA / "runtime.toml").read_text()
    missing = []
    for path in paths:
        if ROOTFS not in path.parents:
            continue
        src = "@self/" + str(path.relative_to(GAIA))
        match = re.search(rf'^id = "([^"]+)"\nsrc = "{re.escape(src)}"', runtime, re.M)
        if not match or f'"{match.group(1)}"' not in runtime.split("[image.feed]", 1)[-1]:
            missing.append(str(path.relative_to(ROOT)))
    return missing


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="print a diff and exit 1 instead of writing")
    parser.add_argument(
        "--lemnos-ctl",
        default=os.environ.get("LEMNOS_CTL") or shutil.which("lemnos-ctl"),
        help="a lemnos-ctl to run `validate` on board.toml with (default $LEMNOS_CTL, else one on PATH)",
    )
    args = parser.parse_args()

    try:
        manifest = json.loads(MANIFEST.read_text())
        lint(manifest)
        files = outputs(manifest)
    except (LintError, KeyError, ValueError) as error:
        print(f"gen-raze: {SOURCE}: {error}", file=sys.stderr)
        return 1

    stale = []
    for path, text in files.items():
        current = path.read_text() if path.exists() else ""
        if current == text:
            continue
        stale.append(path)
        rel = str(path.relative_to(ROOT))
        if args.check:
            sys.stdout.writelines(
                difflib.unified_diff(
                    current.splitlines(True), text.splitlines(True), f"a/{rel}", f"b/{rel} (from the manifest)"
                )
            )
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(f"gen-raze: wrote {rel}")

    if args.lemnos_ctl:
        with tempfile.TemporaryDirectory() as tmp:
            board = Path(tmp) / "board.toml"
            board.write_text(files[BOARD_TOML])
            ok, said = raze_lemnos.lemnos_ctl_validate(args.lemnos_ctl, board)
        print(f"gen-raze: lemnos-ctl validate: {said.replace(str(board), 'board.toml')}", file=sys.stderr)
        if not ok:
            return 1

    unstaged = staged_in_runtime(list(files))
    for rel in unstaged:
        print(f"gen-raze: {rel} is not staged and fed in gaia/runtime.toml", file=sys.stderr)

    if args.check and stale:
        print(
            f"gen-raze: {len(stale)} file(s) disagree with {SOURCE}; run {TOOL} and commit the result",
            file=sys.stderr,
        )
        return 1
    return 1 if unstaged else 0


if __name__ == "__main__":
    sys.exit(main())
